### PR TITLE
Configure Azure pipelines

### PR DESCRIPTION
**Pull request by kenzabou**
This pipeline configuration builds the application and produces a build for the Release configuration.

### CODE REVIEW

**Comment by DhanaprakashK** [comment]
Changed for Pull Request

**Comment by ganeshduvvuri20** [comment]
configure build pipeline which producces aritifcats for release

**Comment by 12920** [comment]
This pipeline configuration builds the application and produces a build for the Release configuration.

**Comment by khanfe** [comment]
merge

**Pull request closed without merging**
